extends Node

const GAME_SET_START_TIME = 'GAME_SET_START_TIME'

const PLAYER_DAMAGE = 'PLAYER_DAMAGE'
const PLAYER_ADD_GOLD = 'PLAYER_ADD_GOLD'
const PLAYER_SET_GOLD = 'PLAYER_SET_GOLD'
const PLAYER_SET_HEALTH = 'PLAYER_SET_HEALTH'
